name: Deploy Frontend Guematrialab

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          cd /var/www/apps/frontend-guematrialab/deepgematrialab
          git fetch origin
          git reset --hard origin/main
          npm install --legacy-peer-deps
          CI=false npm run build
